import barcelona1 from './barcelona1.jpg';
import barcelona2 from './barcelona2.jpg';
import barcelona3 from './barcelona3.jpg';
import barcelona4 from './barcelona4.jpg';
import barcelona5 from './barcelona5.jpg';
import madrid1 from './madrid1.jpg';
import madrid2 from './madrid2.jpg';
import madrid3 from './madrid3.jpg';
import madrid4 from './madrid4.jpg';
import madrid5 from './madrid5.jpg';
import granada1 from './granada1.jpg';
import granada2 from './granada2.jpg';
import granada3 from './granada3.jpg';
import granada4 from './granada4.jpg';
import granada5 from './granada5.jpg';


export const data = [
    {
        id: 1,
        cityName: "Barcelona",
        placeName: ["The Sagrada Família", "Park Guell", "Casa Mila", "La Boqueria", "Casa Batlló"],
        image: [barcelona1, barcelona2, barcelona3, barcelona4, barcelona5],
        description: ["The Basílica i Temple Expiatori de la Sagrada Família also known as the Sagrada Família, is a large unfinished minor basilica in the Eixample district of Barcelona, Catalonia, Spain, and is currently the largest unfinished Roman Catholic church. Designed by the Catalan architect Antoni Gaudí, his work on the building is part of a UNESCO World Heritage Site. On 7 November 2010, Pope Benedict XVI consecrated the church and proclaimed it a minor basilica. On 19 March 1882, construction of the Sagrada Família began under architect Francisco de Paula del Villar. In 1883, when Villar resigned, Gaudí took over as chief architect, transforming the project with his architectural and engineering style, combining Gothic and curvilinear Art Nouveau forms. Gaudí devoted the remainder of his life to the project, and he is buried in the crypt. At the time of his death in 1926, less than a quarter of the project was complete.", 
                      "Park Güell is the reflection of Gaudí's artistic plenitude, which belongs to his naturalist phase (first decade of the 20th century). During this period, the architect perfected his personal style through inspiration from organic shapes. He put into practice a series of new structural solutions rooted in the analysis of geometry. To that, the Catalan artist adds creative liberty and an imaginative, ornamental creation. Starting from a sort of baroquism, his works acquire a structural richness of forms and volumes, free of the rational rigidity or any sort of classic premises. In the design of Park Güell, Gaudí unleashed all his architectonic genius and put to practice much of his innovative structural solutions that would become the symbol of his organic style.",
                      "Casa Milà popularly known as La Pedrera or *The stone quarry*, a reference to its unconventional rough-hewn appearance, is a Modernista building in Barcelona, Catalonia, Spain. It was the last private residence designed by architect Antoni Gaudí and was built between 1906 and 1912. The building was commissioned in 1906 by Pere Milà and his wife Roser Segimon. At the time, it was controversial because of its undulating stone facade, twisting wrought iron balconies and designed by Josep Maria Jujol. Several structural innovations include a self-supporting stone façade, and a free-plan floor, underground garage and the spectacular terrace on the roof. In 1984, it was declared a World Heritage Site by UNESCO.",
                      "The first mention of the Boqueria market in Barcelona dates from 1217, when tables were installed near the old city gate to sell meat. From December 1470 onwards, a pig market was held at this site; at this time it was known as Mercadi Bornet. Later, until 1794, it was known simply as Mercat de la Palla, or straw market. Later, the authorities decided to construct a separate market on La Rambla, housing mainly fishmongers and butchers. It was not until 1826 that the market was legally recognized, and a convention held in 1835, decided to build an official structure. Construction began on March 19, 1840 under the direction of the architect Mas Vilá. The market officially opened in the same year, but the plans for the building were modified many times.",
                      "Casa Batlló is a building in the center of Barcelona. It was designed by Antoni Gaudí, and is considered one of his masterpieces. A remodel of a previously built house, it was redesigned in 1904 by Gaudí and has been refurbished several times after that. Gaudí's assistants Domènec Sugrañes i Gras, Josep Canaleta and Joan Rubió also contributed to the renovation project. The local name for the building is Casa dels ossos (House of Bones), as it has a visceral, skeletal organic quality. It is located on the Passeig de Gràcia in the Eixample district, and forms part of a row of houses known as the Illa de la Discòrdia, which consists of four buildings by noted Modernista architects of Barcelona."
        ],
        showMore: false
    },

    {
        id: 2,
        cityName: "Madrid",
        placeName: ["The Prado Museum", "The Buen Retiro Park", "The Royal Palace of Madrid", "Plaza Mayor", "Queen Sofía National Museum Art Centre"],
        image: [madrid1, madrid2, madrid3, madrid4, madrid5],
        description: ["The Prado Museum, officially known as Museo Nacional del Prado, is the main Spanish national art museum, located in central Madrid. It is widely considered to house one of the world's finest collections of European art, dating from the 12th century to the early 20th century, based on the former Spanish Royal Collection, and the single best collection of Spanish art. Founded as a museum of paintings and sculpture in 1819, it also contains important collections of other types of works. The Prado Museum is one of the most visited sites in the world, and is considered one of the greatest art museums in the world. The numerous works by Francisco Goya, the single most extensively represented artist, as well as by Hieronymus Bosch, El Greco, Peter Paul Rubens, Titian, and Diego Velázquez, are some of the highlights of the collection. Velázquez and his keen eye and sensibility were also responsible for bringing much of the museum's fine collection of Italian masters to Spain, now the largest outside Italy.",
                      "The Buen Retiro Park is one of the largest parks of the city of Madrid, Spain. The park belonged to the Spanish Monarchy until the late 19th century, when it became a public park. In 2021, Buen Retiro Park became part of a combined UNESCO World Heritage Site with Paseo del Prado. The Buen Retiro Park is a large and popular 1.4 km2 (350 acres) park at the edge of the city centre, very close to the Puerta de Alcalá and not far from the Prado Museum. On its grounds are gardens, statues and other monuments, galleries, an artificial lake, and venues which host a variety of events. The park is entirely surrounded by the present-day city.",
                      "The Royal Palace of Madrid is the official residence of the Spanish royal family at the city of Madrid, although now used only for state ceremonies. The palace has 135,000 m2 (1,450,000 sq ft) of floor space and contains 3,418 rooms. It is the largest functioning royal palace and the largest by floor area in Europe. The palace is now open to the public, except during state functions, although it is so large that only a selection of rooms are on the visitor route at any one time, the route being changed every few months. An admission fee of €13 is charged; however, at some times it is free. The palace is owned by the Spanish state and administered by the Patrimonio Nacional, a public agency of the Ministry of the Presidency. The palace is on Bailén Street in the western part of downtown Madrid, east of the Manzanares River, and is accessible from the Ópera metro station. Felipe VI and the royal family do not reside in the palace.",
                      "The Plaza Mayor (English: Town square) is a major public space in the heart of Madrid, the capital of Spain. It was once the centre of Old Madrid. It was first built (1580–1619) during the reign of Philip III. Only a few blocks away is another famous plaza, the Puerta del Sol. The Plaza Mayor dates back to the 15th century where it was originally called the Plaza del Arrabal and was used as the main market of the town. In 1561, the plaza was transferred to the city of Madrid.",
                      "Queen Sofía National Museum Art Centre is Spain's national museum of 20th-century art. The museum was officially inaugurated on September 10, 1990, and is named for Queen Sofía. It is located in Madrid, near the Atocha train and metro stations, at the southern end of the so-called Golden Triangle of Art (located along the Paseo del Prado and also comprising the Museo del Prado and the Museo Thyssen-Bornemisza). The museum is mainly dedicated to Spanish art. Highlights of the museum include excellent collections of Spain's two greatest 20th-century masters, Pablo Picasso and Salvador Dalí. The most famous masterpiece in the museum is Picasso's 1937 painting Guernica. Along with its extensive collection, the museum offers a mixture of national and international temporary exhibitions in its many galleries, making it one of the world's largest museums for modern and contemporary art."
        ],
        showMore: false
    },

    {
        id: 3,
        cityName: "Granada",
        placeName: ["The Alhambra", "The Generalife", "Granada Cathedral", "Nasrid Palaces", "Mirador de San Nicolás"],
        image: [granada1, granada2, granada3, granada4, granada5],
        description: ["The Alhambra is a palace and fortress complex located in Granada, Andalusia, Spain. It is one of the most famous monuments of Islamic architecture and one of the best-preserved palaces of the historic Islamic world, in addition to containing notable examples of Spanish Renaissance architecture. The complex was begun in 1238 by Muhammad I Ibn al-Ahmar, the first Nasrid emir and founder of the Emirate of Granada, the last Muslim state of Al-Andalus. It was built on the Sabika hill, an outcrop of the Sierra Nevada which had been the site of earlier fortresses and of the 11th-century palace of Samuel ibn Naghrillah. Later Nasrid rulers continuously modified the site. The most significant construction campaigns, which gave the royal palaces much of their definitive character, took place in the 14th century during the reigns of Yusuf I and Muhammad V. After the conclusion of the Christian Reconquista in 1492, the site became the Royal Court of Ferdinand and Isabella (where Christopher Columbus received royal endorsement for his expedition), and the palaces were partially altered.",
                      "The Generalife was a summer palace and country estate of the Nasrid rulers of the Emirate of Granada in Al-Andalus. It is located directly east of and uphill from the Alhambra palace complex in Granada, Spain. The Generalife today includes a mix of original Nasrid-period elements as well as extensive modern elements (especially in the appearance of the gardens). The walkways are paved in traditional Granadian style with a mosaic of pebbles: white ones from the River Darro and black ones from the River Genil.",
                      "Granada Cathedral, or the Cathedral of the Incarnation is a Roman Catholic church in the city of Granada, capital of the province of the same name in the Autonomous Region of Andalusia, Spain. The cathedral is the seat of the Archdiocese of Granada. Like many other cathedrals in Andalusia, it was built on top of the city's main mosque after the reconquest of Granada. Unlike most cathedrals in Spain, construction was not begun until the sixteenth century in 1518 in the centre of the old Muslim Medina, after acquisition of the Nasrid kingdom of Granada from its Muslim rulers in 1492. While its earliest plans had Gothic designs, such as are evident in the Royal Chapel of Granada by Enrique Egas, most of the church's construction occurred when the Spanish Renaissance style was supplanting the Gothic in Spanish architecture.",
                      "Mohammed ben Al-Hamar (Mohammed I) was the first king to move to the Alcazaba and no records about a new palace being built are kept until those of Abu l-Walid Ismail (fifth king of the dynasty). A palace was built near the Great Mosque (Gran Mezquita) but only the Mexuar is now left because Yusuf I destroyed it completely. He started some improvements in the Comares Tower (Torre de Comares), the Court of the Myrtles (Patio de los Arrayanes) and the Baths (Baños). These improvements were finished by Mohammed V, who added them all to the Mexuar, extended the gallery that would later be called Machuca and constructed the Palace of the Lions (Palacio de los Leones). These two kings were the most important ones as regards the construction, reconstruction, and decoration of the Alhambra. There are three independent areas in the Nasrid Palaces (Palacios Nazaríes): the Mexuar, which corresponds to the semipublic part of the palace or selamlik, for justice administration and State affairs; the Comares Palace (Palacio de Comares), which was the official residence of the king; and the Palace of the Lions (Palacio de los Leones), which was the private area of the palace, where the Harem was located. Not only were these areas different because of their functions, but also because of their artistic characteristics. The Comares Palace (Palacio de Comares) was decorated in a typically Muslim way, but the Palace of the Lions (Patio de los Leones) presents Christian influences, probably as a consequence of the friendship between Mohammed V and his Castilian counterpart Pedro I, the Cruel.",
                      "The Mirador de San Nicolás is perhaps the most famous viewpoint in Granada. Since ex-US president Bill Clinton visited in 1997 and said it has the most beautiful sunset in the world, the Mirador de San Nicolás has become a must-see for tourists. The beauty of this viewpoint is undeniable, with the Alhambra and the Generalife face to face, the city at its feet, and the magnificent Sierra Nevada behind. The Mirador is located in the Albayzin neighbourhood and is famous for the charm of its surroundings, its cobbled streets, white houses, tapas bars, and its people. Just next to the viewpoint is the Church of San Nicolás of 1525 in the Mudejar and Gothic style, built on a mosque like many other churches in Granada."
        ],
        showMore: false
    }
]